[package]
name = "web_scraper3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webdriver = "0.46.0"
fantoccini = "0.19.3"
tokio = { version = "1", features = ["full"] }

visdom = "0.5.5"

rusqlite = { version = "0.28.0", features = ["bundled"] }
tokio-rusqlite = "0.3.0"

# 下载
reqwest = { version = "0.11.12", features = ["stream"] }
futures-util = "0.3.24"

# 加密名字用
base64 = "0.13.0"

# 初始化浏览器capability
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.85"