[package]
name = "web_scraper3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fantoccini = "0.19.3"
tokio = { version = "1", features = ["full"] }

visdom = "0.5.5"

rusqlite = { version = "0.28.0", features = ["bundled"] }
tokio-rusqlite = "0.3.0"