[package]
name = "web_scraper3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webdriver = "0.46.0"
fantoccini = "0.19.3"
tokio = { version = "1", features = ["full"] }

visdom = "0.5.5"

rusqlite = { version = "0.28.0", features = ["bundled"] }
tokio-rusqlite = "0.3.0"

# 下载
reqwest = { version = "0.11.12", features = ["stream","blocking"] }
futures-util = "0.3.24"

# 加密名字用
base64 = "0.13.0"

# 初始化浏览器capability
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.85"

# 压缩文件处理
zip = "0.6.2"

# 错误处理
anyhow = "1.0.65"

# 系统信息
sysinfo = "0.26.4"

# 音乐
rodio = { version = "0.16.0", features = ["mp3", "wav", "flac"] }
mp3-duration = "0.1.10"

soloud = "1.0.2"  
#{ git = "https://github.com/moalyousef/soloud-rs" }

# notify 监控文件｜文件夹 变化
notify = "5.0.0"

# 推断文件类型
infer = "0.9.0"
# 想做tiff 文件 转jpeg
# magick_rust = "0.16.0"
image = "0.24.4"

# cli framework
seahorse = "2.1.0"

# 正则
regex = "1"
lazy_static = "1.4.0"