[package]
name = "web_http_request"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.25", features = ["full"] } 
tokio = { version = "1.26.0", features = ["full"] }

reqwest = { version = "0.11.14", features = ["json"] }
# 重试机制
# reqwest-middleware = "0.1.1"
# reqwest-retry = "0.1.1"