[package]
name = "cookbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wena = "0.2.0"
colored = "2.0.0"

whale = { path = "../../whale" }