[package]
name = "hi_redis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.22.3"

rust-crypto = "0.2.36"

serde = { version = "1.0.152", features = ["derive"] }

serde_json = "1.0.93"