[package]
name = "global_states"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"
lazy_static = "1.4.0"
once_cell = "1.17.1"

[dev-dependencies]
static_assertions = "1.1.0"
