[package]
name = "db_diesel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# diesel = { version = "2.0.0", features = ["sqlite"] }
diesel = { version = "2.0.0", features = ["sqlite","r2d2"] }
dotenvy = "0.15"


serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
anyhow = "1.0"
chrono = "0.4.15"