[package]
name = "black_hat_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.10.1"
hex = "0.4.3"

# error-handling
thiserror = "1.0.38"
anyhow = "1.0.69"

# 并发