[package]
name = "hi_js"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 备选 boa_engine
deno_core = "0.270.0"
tokio = { version = "1.19.1", features = ["full"] }