[package]
name = "db_sqlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.28.0", features = ["chrono"] }

## sql query builder 支持
chrono = { version = "^0.4", default-features = false, features = ["clock"] }
time = { version = "^0.3", features = ["parsing", "macros"] }
serde_json = { version = "^1" }
# rusqlite only supports uuid 0
uuid = { version = "^1", features = ["serde", "v4"] }
sea-query = { version = "^0"}
# sea-query-rusqlite = { version = "^0", features = [ "with-chrono","with-json","with-uuid","with-time"] }

# orm 这个跟rusqlite库好像是互斥的 
# sea-orm = { version = "0.9.2",features = [ "sqlx-sqlite", "runtime-async-std-rustls","macros" ] }

[dependencies.async-std]
version = "1.7.0"
# default-features = false
features = ["std"]