[package]
name = "db_sqlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.28.0"

# orm
# sea-orm = { version = "0.9.2",features = [ "sqlx-sqlite", "runtime-async-std-rustls","macros" ] }

[dependencies.async-std]
version = "1.7.0"
# default-features = false
features = ["std"]